### ISSUE TITLE
Fatal exception on android

### ISSUE THREAD

**Issue by tqm-dev** [symbol/sdk-java#13]
Getting the error below when I try to do my small test using sdk-java.
The problem might be related to the changes of Conscrypt since Android Pie (Version 9)

```
    --------- beginning of crash
2022-12-11 16:44:47.686 21682-21711/com.symbol.spina E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.symbol.spina, PID: 21682
    io.nem.symbol.core.crypto.CryptoException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$1(Hashes.java:162)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda1.apply(Unknown Source:2)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:84)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152)
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124)
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39)
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34)
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50)
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82)
        at com.symbol.spina.AccountGenThread.run(ExampleInstrumentedTest.kt:22)
     Caused by: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:563)
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:330)
        at java.security.MessageDigest.getInstance(MessageDigest.java:261)
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$0(Hashes.java:154)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda0.call(Unknown Source:4)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:72)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152) 
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39) 
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34) 
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50) 
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82) 

```

1. Expected behavior and actual behavior.
  No error or exception on android when the account creation.

2. Steps to reproduce the problem.
  On android 11, 
  Execute below thread with AccountGenThread().start()  written in kotlin

```
  class AccountGenThread : Thread() {
    override fun run(){
        val bob = Account.generateNewAccount(NetworkType.MAIN_NET)
        Log.d("test-java-sdk", "Bob address is: ${bob.address.plain()}")
    }
}
```
    
3. Specifications like the version of the project, operating system, or hardware.
  
  > Android 11
  > Android Studio (Windows 10)
  > On build.gradle, import the client impl like below:
      implementation "io.nem:symbol-sdk-okhttp-client:1.0.2" 
  
 thanks

**Comment by cryptoBeliever** [comment]
Hello @tqm-dev. Could you confirm the same error you have on 1.0.1 and 1.0.3?

**Comment by tqm-dev** [comment]
@cryptoBeliever 

Yes.

Getting the same error . see the log below:

on implementation "io.nem:symbol-sdk-okhttp-client:1.0.1"

```
2022-12-11 21:29:59.879 31644-31670/com.symbol.spina E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.symbol.spina, PID: 31644
    io.nem.symbol.core.crypto.CryptoException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$1(Hashes.java:162)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda1.apply(Unknown Source:2)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:84)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152)
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124)
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39)
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34)
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50)
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82)
        at com.symbol.spina.AccountGenThread.run(ExampleInstrumentedTest.kt:22)
     Caused by: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:563)
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:330)
        at java.security.MessageDigest.getInstance(MessageDigest.java:261)
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$0(Hashes.java:154)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda0.call(Unknown Source:4)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:72)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152) 
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39) 
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34) 
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50) 
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82) 
        at com.symbol.spina.AccountGenThread.run(ExampleInstrumentedTest.kt:22) 

```

on implementation "io.nem:symbol-sdk-okhttp-client:1.0.3"

```
2022-12-11 21:37:27.479 31965-31993/com.symbol.spina E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.symbol.spina, PID: 31965
    io.nem.symbol.core.crypto.CryptoException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$1(Hashes.java:162)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda1.apply(Unknown Source:2)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:84)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152)
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124)
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39)
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71)
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34)
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50)
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82)
        at com.symbol.spina.AccountGenThread.run(ExampleInstrumentedTest.kt:22)
     Caused by: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for MessageDigest.SHA512.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:563)
        at sun.security.jca.Providers.checkBouncyCastleDeprecation(Providers.java:330)
        at java.security.MessageDigest.getInstance(MessageDigest.java:261)
        at io.nem.symbol.core.crypto.Hashes.lambda$hash$0(Hashes.java:154)
        at io.nem.symbol.core.crypto.Hashes$$ExternalSyntheticLambda0.call(Unknown Source:4)
        at io.nem.symbol.core.utils.ExceptionUtils.propagate(ExceptionUtils.java:72)
        at io.nem.symbol.core.crypto.Hashes.hash(Hashes.java:152) 
        at io.nem.symbol.core.crypto.Hashes.sha512(Hashes.java:124) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519Utils.prepareForScalarMultiply(Ed25519Utils.java:37) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.derivePublicKey(Ed25519KeyGenerator.java:39) 
        at io.nem.symbol.core.crypto.KeyPair.fromPrivate(KeyPair.java:71) 
        at io.nem.symbol.core.crypto.ed25519.Ed25519KeyGenerator.generateKeyPair(Ed25519KeyGenerator.java:34) 
        at io.nem.symbol.core.crypto.KeyPair.random(KeyPair.java:50) 
        at io.nem.symbol.sdk.model.account.Account.generateNewAccount(Account.java:82) 
        at com.symbol.spina.AccountGenThread.run(ExampleInstrumentedTest.kt:22) 

```

thank you for your support.

**Comment by cryptoBeliever** [comment]
@tqm-dev according to https://stackoverflow.com/a/66323575 Android has a built-in BC provider with limited algorithms available.
That's why the BC provider in SDK is not loaded correctly (because another already exists): https://github.com/symbol/sdk-java/blob/dev/sdk-core/src/main/java/io/nem/symbol/core/crypto/Hashes.java#L154

As a workaround, you could remove the build-in provider before you will use SDK and the correct BC provider will be added:

```
Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME)
```

**Comment by tqm-dev** [comment]
@cryptoBeliever 

I tried the workaround you suggested when my app launched.

```
    init {
        Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME)
        Security.addProvider(BouncyCastleProvider())
    }

```

Everything I needed is working fine.
Thank you. 

I am going to build something new for symbol.

**Comment by cryptoBeliever** [comment]
Great. Nice to hear that. I'm looking forward to what you build :)
